//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.06 at 01:32:42 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(xmlns = { @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://prov-callback.eagle.vodafone.com.eg", prefix = "") }, namespace = "http://prov-callback.eagle.vodafone.com.eg", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.edafa.web2sms.prov.cloud.model.callback;

