//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.15 at 02:10:57 PM EEST 
//

package com.edafa.web2sms.prov.cloud.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ProvisioningBaseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ProvisioningBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompanyID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubscriptionID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProvisioningID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AccountHolderID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CallbackURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MSISDN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProvisioningBaseType", propOrder = { "companyID", "companyDomain", "subscriptionID", "provisioningID",
		"accountHolderID", "callbackURL", "msisdn" })
@XmlSeeAlso({ CompanySubscriptionProvisionFullInfoType.class, UserProvisionBaseType.class })
public class ProvisioningBaseType {

	@XmlElement(name = "CompanyID", required = true)
	protected String companyID;
	@XmlElement(name = "CompanyDomain", required = true)
	protected String companyDomain;
	@XmlElement(name = "SubscriptionID", required = true)
	protected String subscriptionID;
	@XmlElement(name = "ProvisioningID", required = true)
	protected String provisioningID;
	@XmlElement(name = "AccountHolderID", required = true)
	protected String accountHolderID;
	@XmlElement(name = "CallbackURL", required = true)
	protected String callbackURL;
	@XmlElement(name = "MSISDN")
	protected String msisdn;

	@XmlTransient
	protected String typeName;

	/**
	 * Gets the value of the companyID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCompanyID() {
		return companyID;
	}

	/**
	 * Sets the value of the companyID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCompanyID(String value) {
		this.companyID = value;
	}

	/**
	 * Gets the value of the companyDomain property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCompanyDomain() {
		return companyDomain;
	}

	/**
	 * Sets the value of the companyDomain property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCompanyDomain(String value) {
		this.companyDomain = value;
	}

	/**
	 * Gets the value of the subscriptionID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubscriptionID() {
		return subscriptionID;
	}

	/**
	 * Sets the value of the subscriptionID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubscriptionID(String value) {
		this.subscriptionID = value;
	}

	/**
	 * Gets the value of the provisioningID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProvisioningID() {
		return provisioningID;
	}

	/**
	 * Sets the value of the provisioningID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProvisioningID(String value) {
		this.provisioningID = value;
	}

	/**
	 * Gets the value of the accountHolderID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAccountHolderID() {
		return accountHolderID;
	}

	/**
	 * Sets the value of the accountHolderID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAccountHolderID(String value) {
		this.accountHolderID = value;
	}

	/**
	 * Gets the value of the callbackURL property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCallbackURL() {
		return callbackURL;
	}

	/**
	 * Sets the value of the callbackURL property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCallbackURL(String value) {
		this.callbackURL = value;
	}

	/**
	 * Gets the value of the msisdn property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMSISDN() {
		return msisdn;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * Sets the value of the msisdn property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMSISDN(String value) {
		this.msisdn = value;
	}

	@XmlTransient
	public boolean isValid() {
		boolean valid = true;
		if (companyID == null || companyID.isEmpty() || accountHolderID == null || accountHolderID.isEmpty()
				|| provisioningID == null || provisioningID.isEmpty() || subscriptionID == null
				|| subscriptionID.isEmpty() || callbackURL == null || callbackURL.isEmpty()) {
			valid = false;
		}
		return valid;
	}

/*	@Override
	public String toString() {
		return typeName + "(" + provisioningID + ") companyID=" + companyID + ", companyDomain=" + companyDomain
				+ ", subscriptionID=" + subscriptionID + ", provisioningID=" + provisioningID + ", accountHolderID="
				+ accountHolderID + ", callbackURL=" + callbackURL + ", msisdn=" + msisdn;
	}
*/
	
	@XmlTransient
	public String logId() {
		if (provisioningID != null)
			return getTypeName() + "(" + provisioningID + "): ";
		else
			return getClass().getSimpleName() + ": ";
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ProvisioningBaseType [");
		if (companyID != null) {
			builder.append("companyID=");
			builder.append(companyID);
			builder.append(", ");
		}
		if (companyDomain != null) {
			builder.append("companyDomain=");
			builder.append(companyDomain);
			builder.append(", ");
		}
		if (subscriptionID != null) {
			builder.append("subscriptionID=");
			builder.append(subscriptionID);
			builder.append(", ");
		}
		if (provisioningID != null) {
			builder.append("provisioningID=");
			builder.append(provisioningID);
			builder.append(", ");
		}
		if (accountHolderID != null) {
			builder.append("accountHolderID=");
			builder.append(accountHolderID);
			builder.append(", ");
		}
		if (callbackURL != null) {
			builder.append("callbackURL=");
			builder.append(callbackURL);
			builder.append(", ");
		}
		if (msisdn != null) {
			builder.append("msisdn=");
			builder.append(msisdn);
			builder.append(", ");
		}
		if (typeName != null) {
			builder.append("typeName=");
			builder.append(typeName);
		}
		builder.append("]");
		return builder.toString();
	}

	// @XmlTransient
	// public String logRequest() {
	// StringBuilder logMsg = new StringBuilder();
	// logMsg.append("provisioningID (");
	// logMsg.append(provisioningID);
	// logMsg.append("): requestType=");
	// logMsg.append(getClass().getSimpleName());
	//
	// logMsg.append(", companyDomain=");
	// logMsg.append(companyDomain);
	//
	// logMsg.append(", callbackUrl=");
	// logMsg.append(callbackURL);
	//
	// return logMsg.toString();
	// }

}
