package com.edafa.web2sms.prov.tibco.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.edafa.web2sms.prov.tibco.types.ActivateServiceRequest;
import com.edafa.web2sms.prov.tibco.types.ActivateServiceResponse;
import com.edafa.web2sms.prov.tibco.types.ConfirmSenderNameAddRequest;
import com.edafa.web2sms.prov.tibco.types.ConfirmSenderNameAddResponse;
import com.edafa.web2sms.prov.tibco.types.CancelProvRequest;
import com.edafa.web2sms.prov.tibco.types.CancelProvRequestResponse;
import com.edafa.web2sms.prov.tibco.types.ChangeSenderNameRequest;
import com.edafa.web2sms.prov.tibco.types.ChangeSenderNameResponse;
import com.edafa.web2sms.prov.tibco.types.ConfirmSenderNameChangeRequest;
import com.edafa.web2sms.prov.tibco.types.ConfirmSenderNameChangeResponse;
import com.edafa.web2sms.prov.tibco.types.DeactivateServiceRequest;
import com.edafa.web2sms.prov.tibco.types.DeactivateServiceResponse;
import com.edafa.web2sms.prov.tibco.types.DeleteSenderNameRequest;
import com.edafa.web2sms.prov.tibco.types.DeleteSenderNameResponse;
import com.edafa.web2sms.prov.tibco.types.DowngradeServiceRequest;
import com.edafa.web2sms.prov.tibco.types.DowngradeServiceResponse;
import com.edafa.web2sms.prov.tibco.types.GetAccountInfoRequest;
import com.edafa.web2sms.prov.tibco.types.GetAccountInfoResponse;
import com.edafa.web2sms.prov.tibco.types.ObjectFactory;
import com.edafa.web2sms.prov.tibco.types.UpgradeServiceRequest;
import com.edafa.web2sms.prov.tibco.types.UpgradeServiceResponse;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8-b13937 Generated
 * source version: 2.2
 * 
 */
// @Local
@WebService(name = "Web2SMSTIBCOProvisioning", targetNamespace = "http://www.edafa.com/web2sms/prov/TIBCO")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface Web2SMSTIBCOProvisioning {

	/**
	 * 
	 * @param request
	 * @return returns
	 *         com.edafa.web2sms.service.prov.tibco.types.ProvisioningStatus
	 */
	@WebMethod
	@WebResult(name = "downgradeServiceResponse", partName = "provStatus")
	public DowngradeServiceResponse downgradeService(
			@WebParam(name = "downgradeServiceRequest", partName = "request") DowngradeServiceRequest request);

	/**
	 * 
	 * @param request
	 * @return returns
	 *         com.edafa.web2sms.service.prov.tibco.types.ProvisioningStatus
	 */
	@WebMethod
	@WebResult(name = "upgradeServiceResponse", partName = "provStatus")
	public UpgradeServiceResponse upgradeService(
			@WebParam(name = "upgradeServiceRequest", partName = "request") UpgradeServiceRequest request);

	/**
	 * 
	 * @param request
	 * @return returns
	 *         com.edafa.web2sms.service.prov.tibco.types.ProvisioningStatus
	 */
	@WebMethod
	@WebResult(name = "deactivateServiceResponse", partName = "provStatus")
	public DeactivateServiceResponse deactivateService(
			@WebParam(name = "deactivateServiceRequest", partName = "request") DeactivateServiceRequest request);

	/**
	 * 
	 * @param request
	 * @return returns
	 *         com.edafa.web2sms.service.prov.tibco.types.ProvisioningStatus
	 */
	@WebMethod
	@WebResult(name = "confirmSenderNameAddResponse", partName = "provStatus")
	public ConfirmSenderNameAddResponse confirmSenderNameAdd(
			@WebParam(name = "confirmSenderNameAddRequest", partName = "request") ConfirmSenderNameAddRequest request);

	/**
	 * 
	 * @param request
	 * @return returns
	 *         com.edafa.web2sms.service.prov.tibco.types.ProvisioningStatus
	 */
	@WebMethod
	@WebResult(name = "changeSenderNameResponse", partName = "provStatus")
	public ChangeSenderNameResponse changeSenderName(
			@WebParam(name = "changeSenderNameRequest", partName = "request") ChangeSenderNameRequest request);

	/**
	 * 
	 * @param request
	 * @return returns
	 *         com.edafa.web2sms.service.prov.tibco.types.ProvisioningStatus
	 */
	@WebMethod
	@WebResult(name = "confirmSenderNameChangeResponse", partName = "provStatus")
	public ConfirmSenderNameChangeResponse confirmSenderNameChange(
			@WebParam(name = "confirmSenderNameChangeRequest", partName = "request") ConfirmSenderNameChangeRequest request);

	/**
	 * 
	 * @param request
	 * @return returns
	 *         com.edafa.web2sms.service.prov.tibco.types.ProvisioningStatus
	 */
	@WebMethod
	@WebResult(name = "deleteSenderNameResponse", partName = "provStatus")
	public DeleteSenderNameResponse deleteSenderName(
			@WebParam(name = "deleteSenderNameRequest", partName = "request") DeleteSenderNameRequest request);

	/**
	 * 
	 * @param request
	 * @return returns com.edafa.web2sms.service.prov.tibco.types.AccountInfo
	 */
	@WebMethod
	@WebResult(partName = "accountInfo")
	public GetAccountInfoResponse getAccountInfo(
			@WebParam(name = "getAccountInfoRequest", partName = "request") GetAccountInfoRequest request);

	/**
	 * 
	 * @param request
	 * @return returns
	 *         com.edafa.web2sms.service.prov.tibco.types.ProvisioningStatus
	 */
	@WebMethod
	@WebResult(name = "activateServiceResponse", partName = "provStatus")
	public ActivateServiceResponse activateService(
			@WebParam(name = "activateServiceRequest", partName = "request") ActivateServiceRequest request);

	/**
	 * 
	 * @param request
	 * @return returns
	 *         com.edafa.web2sms.service.prov.tibco.types.CancelProvRequestResponse
	 */
	@WebMethod
	@WebResult(name = "cancelProvRequestResponse", partName = "provStatus")
	public CancelProvRequestResponse cancelProvRequest(
			@WebParam(name = "cancelProvRequestRequest", partName = "request") CancelProvRequest request);

}
