INSERT INTO MODULES (MODULE_ID,MODULE_NAME,DESCRIPTION) VALUES (29,'Reporting',null);

INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2901,29,'ACCOUNT_MANAGEMENT_PROVIDER','t3://10.28.20.71:3572',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2902,29,'ACCOUNT_MANAGEMENT_REMOTE_JNDI','java:global/Web2SMS_Account_Management/Web2SMS_Account_Management_Main/AccountManegementBeanWrapper',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2903,29,'ACCOUNT_MANAGEMENT_REMOTE_POOL_MAXTOTAL','128',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2904,29,'ACCOUNT_MANAGEMENT_REMOTE_POOL_MAXIDLE','64',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2905,29,'ACCOUNT_ADMIN_MANAGEMENT_REMOTE_JNDI','java:global/Web2SMS_Account_Management/Web2SMS_Account_Management_Main/AccountManegementBeanWrapper',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2906,29,'ACCOUNT_ADMIN_MANAGEMENT_REMOTE_POOL_MAXTOTAL','128',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2907,29,'ACCOUNT_ADMIN_MANAGEMENT_REMOTE_POOL_MAXIDLE','64',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2908,29,'ACCOUNT_CONVERSION_REMOTE_JNDI','java:global/Web2SMS_Account_Management/Web2SMS_Account_Management_Main/AccountConversionBeanWrapper',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2909,29,'ACCOUNT_CONVERSION_REMOTE_POOL_MAXTOTAL','128',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2910,29,'ACCOUNT_CONVERSION_REMOTE_POOL_MAXIDLE','64',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2911,29,'ACCOUNT_USER_MANAGEMENT_REMOTE_JNDI','java:global/Web2SMS_Account_Management/Web2SMS_Account_Management_Main/UserManagementBeanWrapper',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2912,29,'ACCOUNT_USER_MANAGEMENT_REMOTE_POOL_MAXTOTAL','128',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2913,29,'ACCOUNT_USER_MANAGEMENT_REMOTE_POOL_MAXIDLE','64',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2914,29,'ACCOUNT_QUOTA_MANAGEMENT_REMOTE_JNDI','java:global/Web2SMS_Account_Management/Web2SMS_Account_Management_Main/AccountQuotaManagementBeanWrapper',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2915,29,'ACCOUNT_QUOTA_MANAGEMENT_REMOTE_POOL_MAXTOTAL','128',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2916,29,'ACCOUNT_QUOTA_MANAGEMENT_REMOTE_POOL_MAXIDLE','64',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2917,29,'ACCOUNT_MANAGEMENT_FACING','REMOTE',null,1);

INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2918,29,'LOG_LEVEL','trace',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2919,29,'LOG_DIR_NAME','logs/',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2920,29,'ALARMING_IDENTIFIER','112',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2921,29,'ReportingServerBaseDir','web2sms-appReporting/',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2922,29,'REPORT_EXPORT_CHUNK_SIZE',50000,null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2923,29,'EXCEL_WINDOW_SIZE',100000,null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2924,29,'EXCEL_SHEET_ROWS_NUM',10000,null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2925,29,'REPORT_EXPORT_CHARSET','UTF-8',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2926,29,'REPORT_EXPORT_PATH','files/exports/reports/',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2927,29,'REPORT_EXPORT_FILE_DELIM',',',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2928,29,'REPORT_EXPORT_FILE_QUOTE_CHAR','\"',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2929,29,'REPORT_EXPORT_FILE_COMPRESSED',true,null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2930,29,'OFFLINE_REPORTS_CONCURRENT_MAX_COUNT',3,null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2931,29,'OFFLINE_REPORTS_MAX_RETRY_COUNT',20,null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2932,29,'ALARM_PATH','alarms/',null,1);

INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (1307,13,'REPORT_WEBSERVICE_URL','http://10.28.20.71:3578/ReportManagementServiceImpl/ReportManagementService?WSDL',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (1010,10,'REPORT_WEBSERVICE_URL','http://10.28.20.71:3578/ReportManagementServiceImpl/ReportManagementService?WSDL',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (1011,10,'REPORTING_MANAGEMENT_CONFIG_WS_URL','http://10.28.20.71:3578/ReportingConfigsManagerServiceImpl/ReportingConfigsManagerService?WSDL',null,1);

-- Admin UI reporting
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (1010,10,'REPORT_WEBSERVICE_URL','http://10.28.20.71:3578/ReportManagementServiceImpl/ReportManagementService?wsdl',null,1);
Insert into SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) values (1012,10,'DOWNLOAD_REPORT_SERVER_LINK','https://10.28.20.71:3578/Web2SMS_Reporting_War/reporting/files/getAdminReport',null,1);
-- UI Modules
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2712,27,'REPORT_WEBSERVICE_URL','http://10.28.20.71:3578/ReportManagementServiceImpl/ReportManagementService?wsdl',null,1);
INSERT INTO SETTINGS (PROPERTY_ID,MODULE,PROPERTY,VALUE,DESCRIPTION,EDIT_FLAG) VALUES (2718,27,'DOWNLOAD_REPORT_SERVER_LINK','https://10.28.20.71:3578/Web2SMS_Reporting_War/reporting/files/getUserReport',null,1);

COMMIT;

