
/* Create Procedure  */

CREATE OR REPLACE PROCEDURE update_collection_stats AS
    v_new_last_update_timestamp TIMESTAMP;
    CURSOR sms_update_set (
        v_end_date TIMESTAMP
    ) IS SELECT /*+ PARALLEL(7) */
        PROCESSING_DATE , 
        PROCESSING_HOUR, 
        
        GROUP_ID, 
        OWNER_ID, 
        STATS_TYPE, 
        
        NVL(VF_NEW_SEG , 0) AS VF_NEW_SEG, 
        NVL(VF_NEW_SMS , 0) AS VF_NEW_SMS, 
        NVL(VF_SUBMITTED_SEG , 0) AS VF_SUBMITTED_SEG, 
        NVL(VF_SUBMITTED_SMS , 0) AS VF_SUBMITTED_SMS, 
        NVL(VF_SENT_SEG , 0) AS VF_SENT_SEG, 
        NVL(VF_SENT_SMS , 0) AS VF_SENT_SMS, 
        NVL(VF_TIMED_OUT_SEG , 0) AS VF_TIMED_OUT_SEG, 
        NVL(VF_TIMED_OUT_SMS , 0) AS VF_TIMED_OUT_SMS, 
        NVL(VF_FAILED_TO_SEND_SEG , 0) AS VF_FAILED_TO_SEND_SEG, 
        NVL(VF_FAILED_TO_SEND_SMS , 0) AS VF_FAILED_TO_SEND_SMS, 
        NVL(VF_DELIVERED_SEG , 0) AS VF_DELIVERED_SEG, 
        NVL(VF_DELIVERED_SMS , 0) AS VF_DELIVERED_SMS, 
        NVL(VF_NOT_DELIVERED_SEG , 0) AS VF_NOT_DELIVERED_SEG, 
        NVL(VF_NOT_DELIVERED_SMS , 0) AS VF_NOT_DELIVERED_SMS, 
        NVL(VF_FAILED_SEG , 0) AS VF_FAILED_SEG, 
        NVL(VF_FAILED_SMS , 0) AS VF_FAILED_SMS, 
        NVL(VF_RECEIVED_SEG , 0) AS VF_RECEIVED_SEG, 
        NVL(VF_RECEIVED_SMS , 0) AS VF_RECEIVED_SMS, 
        NVL(VF_EXPIRED_SEG , 0) AS VF_EXPIRED_SEG, 
        NVL(VF_EXPIRED_SMS , 0) AS VF_EXPIRED_SMS, 
        NVL(VF_UNKNOWN_SEG , 0) AS VF_UNKNOWN_SEG, 
        NVL(VF_UNKNOWN_SMS , 0) AS VF_UNKNOWN_SMS, 
        NVL(VF_PROCESSING_SEG , 0) AS VF_PROCESSING_SEG, 
        NVL(VF_PROCESSING_SMS , 0) AS VF_PROCESSING_SMS, 
        NVL(VF_PARTIAL_DELIVERED_SEG , 0) AS VF_PARTIAL_DELIVERED_SEG, 
        NVL(VF_PARTIAL_DELIVERED_SMS , 0) AS VF_PARTIAL_DELIVERED_SMS, 
        NVL(VF_PARTIAL_RECEIVED_SEG , 0) AS VF_PARTIAL_RECEIVED_SEG, 
        NVL(VF_PARTIAL_RECEIVED_SMS , 0) AS VF_PARTIAL_RECEIVED_SMS, 
        NVL(ET_NEW_SEG , 0) AS ET_NEW_SEG, 
        NVL(ET_NEW_SMS , 0) AS ET_NEW_SMS, 
        NVL(ET_SUBMITTED_SEG , 0) AS ET_SUBMITTED_SEG, 
        NVL(ET_SUBMITTED_SMS , 0) AS ET_SUBMITTED_SMS, 
        NVL(ET_SENT_SEG , 0) AS ET_SENT_SEG, 
        NVL(ET_SENT_SMS , 0) AS ET_SENT_SMS, 
        NVL(ET_TIMED_OUT_SEG , 0) AS ET_TIMED_OUT_SEG, 
        NVL(ET_TIMED_OUT_SMS , 0) AS ET_TIMED_OUT_SMS, 
        NVL(ET_FAILED_TO_SEND_SEG , 0) AS ET_FAILED_TO_SEND_SEG, 
        NVL(ET_FAILED_TO_SEND_SMS , 0) AS ET_FAILED_TO_SEND_SMS, 
        NVL(ET_DELIVERED_SEG , 0) AS ET_DELIVERED_SEG, 
        NVL(ET_DELIVERED_SMS , 0) AS ET_DELIVERED_SMS, 
        NVL(ET_NOT_DELIVERED_SEG , 0) AS ET_NOT_DELIVERED_SEG, 
        NVL(ET_NOT_DELIVERED_SMS , 0) AS ET_NOT_DELIVERED_SMS, 
        NVL(ET_FAILED_SEG , 0) AS ET_FAILED_SEG, 
        NVL(ET_FAILED_SMS , 0) AS ET_FAILED_SMS, 
        NVL(ET_RECEIVED_SEG , 0) AS ET_RECEIVED_SEG, 
        NVL(ET_RECEIVED_SMS , 0) AS ET_RECEIVED_SMS, 
        NVL(ET_EXPIRED_SEG , 0) AS ET_EXPIRED_SEG, 
        NVL(ET_EXPIRED_SMS , 0) AS ET_EXPIRED_SMS, 
        NVL(ET_UNKNOWN_SEG , 0) AS ET_UNKNOWN_SEG, 
        NVL(ET_UNKNOWN_SMS , 0) AS ET_UNKNOWN_SMS, 
        NVL(ET_PROCESSING_SEG , 0) AS ET_PROCESSING_SEG, 
        NVL(ET_PROCESSING_SMS , 0) AS ET_PROCESSING_SMS, 
        NVL(ET_PARTIAL_DELIVERED_SEG , 0) AS ET_PARTIAL_DELIVERED_SEG, 
        NVL(ET_PARTIAL_DELIVERED_SMS , 0) AS ET_PARTIAL_DELIVERED_SMS, 
        NVL(ET_PARTIAL_RECEIVED_SEG , 0) AS ET_PARTIAL_RECEIVED_SEG, 
        NVL(ET_PARTIAL_RECEIVED_SMS , 0) AS ET_PARTIAL_RECEIVED_SMS, 
        NVL(OG_NEW_SEG , 0) AS OG_NEW_SEG, 
        NVL(OG_NEW_SMS , 0) AS OG_NEW_SMS, 
        NVL(OG_SUBMITTED_SEG , 0) AS OG_SUBMITTED_SEG, 
        NVL(OG_SUBMITTED_SMS , 0) AS OG_SUBMITTED_SMS, 
        NVL(OG_SENT_SEG , 0) AS OG_SENT_SEG, 
        NVL(OG_SENT_SMS , 0) AS OG_SENT_SMS, 
        NVL(OG_TIMED_OUT_SEG , 0) AS OG_TIMED_OUT_SEG, 
        NVL(OG_TIMED_OUT_SMS , 0) AS OG_TIMED_OUT_SMS, 
        NVL(OG_FAILED_TO_SEND_SEG , 0) AS OG_FAILED_TO_SEND_SEG, 
        NVL(OG_FAILED_TO_SEND_SMS , 0) AS OG_FAILED_TO_SEND_SMS, 
        NVL(OG_DELIVERED_SEG , 0) AS OG_DELIVERED_SEG, 
        NVL(OG_DELIVERED_SMS , 0) AS OG_DELIVERED_SMS, 
        NVL(OG_NOT_DELIVERED_SEG , 0) AS OG_NOT_DELIVERED_SEG, 
        NVL(OG_NOT_DELIVERED_SMS , 0) AS OG_NOT_DELIVERED_SMS, 
        NVL(OG_FAILED_SEG , 0) AS OG_FAILED_SEG, 
        NVL(OG_FAILED_SMS , 0) AS OG_FAILED_SMS, 
        NVL(OG_RECEIVED_SEG , 0) AS OG_RECEIVED_SEG, 
        NVL(OG_RECEIVED_SMS , 0) AS OG_RECEIVED_SMS, 
        NVL(OG_EXPIRED_SEG , 0) AS OG_EXPIRED_SEG, 
        NVL(OG_EXPIRED_SMS , 0) AS OG_EXPIRED_SMS, 
        NVL(OG_UNKNOWN_SEG , 0) AS OG_UNKNOWN_SEG, 
        NVL(OG_UNKNOWN_SMS , 0) AS OG_UNKNOWN_SMS, 
        NVL(OG_PROCESSING_SEG , 0) AS OG_PROCESSING_SEG, 
        NVL(OG_PROCESSING_SMS , 0) AS OG_PROCESSING_SMS, 
        NVL(OG_PARTIAL_DELIVERED_SEG , 0) AS OG_PARTIAL_DELIVERED_SEG, 
        NVL(OG_PARTIAL_DELIVERED_SMS , 0) AS OG_PARTIAL_DELIVERED_SMS, 
        NVL(OG_PARTIAL_RECEIVED_SEG , 0) AS OG_PARTIAL_RECEIVED_SEG, 
        NVL(OG_PARTIAL_RECEIVED_SMS , 0) AS OG_PARTIAL_RECEIVED_SMS, 
        NVL(WE_NEW_SEG , 0) AS WE_NEW_SEG, 
        NVL(WE_NEW_SMS , 0) AS WE_NEW_SMS, 
        NVL(WE_SUBMITTED_SEG , 0) AS WE_SUBMITTED_SEG, 
        NVL(WE_SUBMITTED_SMS , 0) AS WE_SUBMITTED_SMS, 
        NVL(WE_SENT_SEG , 0) AS WE_SENT_SEG, 
        NVL(WE_SENT_SMS , 0) AS WE_SENT_SMS, 
        NVL(WE_TIMED_OUT_SEG , 0) AS WE_TIMED_OUT_SEG, 
        NVL(WE_TIMED_OUT_SMS , 0) AS WE_TIMED_OUT_SMS, 
        NVL(WE_FAILED_TO_SEND_SEG , 0) AS WE_FAILED_TO_SEND_SEG, 
        NVL(WE_FAILED_TO_SEND_SMS , 0) AS WE_FAILED_TO_SEND_SMS, 
        NVL(WE_DELIVERED_SEG , 0) AS WE_DELIVERED_SEG, 
        NVL(WE_DELIVERED_SMS , 0) AS WE_DELIVERED_SMS, 
        NVL(WE_NOT_DELIVERED_SEG , 0) AS WE_NOT_DELIVERED_SEG, 
        NVL(WE_NOT_DELIVERED_SMS , 0) AS WE_NOT_DELIVERED_SMS, 
        NVL(WE_FAILED_SEG , 0) AS WE_FAILED_SEG, 
        NVL(WE_FAILED_SMS , 0) AS WE_FAILED_SMS, 
        NVL(WE_RECEIVED_SEG , 0) AS WE_RECEIVED_SEG, 
        NVL(WE_RECEIVED_SMS , 0) AS WE_RECEIVED_SMS, 
        NVL(WE_EXPIRED_SEG , 0) AS WE_EXPIRED_SEG, 
        NVL(WE_EXPIRED_SMS , 0) AS WE_EXPIRED_SMS, 
        NVL(WE_UNKNOWN_SEG , 0) AS WE_UNKNOWN_SEG, 
        NVL(WE_UNKNOWN_SMS , 0) AS WE_UNKNOWN_SMS, 
        NVL(WE_PROCESSING_SEG , 0) AS WE_PROCESSING_SEG, 
        NVL(WE_PROCESSING_SMS , 0) AS WE_PROCESSING_SMS, 
        NVL(WE_PARTIAL_DELIVERED_SEG , 0) AS WE_PARTIAL_DELIVERED_SEG, 
        NVL(WE_PARTIAL_DELIVERED_SMS , 0) AS WE_PARTIAL_DELIVERED_SMS, 
        NVL(WE_PARTIAL_RECEIVED_SEG , 0) AS WE_PARTIAL_RECEIVED_SEG, 
        NVL(WE_PARTIAL_RECEIVED_SMS , 0) AS WE_PARTIAL_RECEIVED_SMS, 
        NVL(INTER_NEW_SEG , 0) AS INTER_NEW_SEG, 
        NVL(INTER_NEW_SMS , 0) AS INTER_NEW_SMS, 
        NVL(INTER_SUBMITTED_SEG , 0) AS INTER_SUBMITTED_SEG, 
        NVL(INTER_SUBMITTED_SMS , 0) AS INTER_SUBMITTED_SMS, 
        NVL(INTER_SENT_SEG , 0) AS INTER_SENT_SEG, 
        NVL(INTER_SENT_SMS , 0) AS INTER_SENT_SMS, 
        NVL(INTER_TIMED_OUT_SEG , 0) AS INTER_TIMED_OUT_SEG, 
        NVL(INTER_TIMED_OUT_SMS , 0) AS INTER_TIMED_OUT_SMS, 
        NVL(INTER_FAILED_TO_SEND_SEG , 0) AS INTER_FAILED_TO_SEND_SEG, 
        NVL(INTER_FAILED_TO_SEND_SMS , 0) AS INTER_FAILED_TO_SEND_SMS, 
        NVL(INTER_DELIVERED_SEG , 0) AS INTER_DELIVERED_SEG, 
        NVL(INTER_DELIVERED_SMS , 0) AS INTER_DELIVERED_SMS, 
        NVL(INTER_NOT_DELIVERED_SEG , 0) AS INTER_NOT_DELIVERED_SEG, 
        NVL(INTER_NOT_DELIVERED_SMS , 0) AS INTER_NOT_DELIVERED_SMS, 
        NVL(INTER_FAILED_SEG , 0) AS INTER_FAILED_SEG, 
        NVL(INTER_FAILED_SMS , 0) AS INTER_FAILED_SMS, 
        NVL(INTER_RECEIVED_SEG , 0) AS INTER_RECEIVED_SEG, 
        NVL(INTER_RECEIVED_SMS , 0) AS INTER_RECEIVED_SMS, 
        NVL(INTER_EXPIRED_SEG , 0) AS INTER_EXPIRED_SEG, 
        NVL(INTER_EXPIRED_SMS , 0) AS INTER_EXPIRED_SMS, 
        NVL(INTER_UNKNOWN_SEG , 0) AS INTER_UNKNOWN_SEG, 
        NVL(INTER_UNKNOWN_SMS , 0) AS INTER_UNKNOWN_SMS, 
        NVL(INTER_PROCESSING_SEG , 0) AS INTER_PROCESSING_SEG, 
        NVL(INTER_PROCESSING_SMS , 0) AS INTER_PROCESSING_SMS, 
        NVL(INTER_PARTIAL_DELIVERED_SEG , 0) AS INTER_PARTIAL_DELIVERED_SEG, 
        NVL(INTER_PARTIAL_DELIVERED_SMS , 0) AS INTER_PARTIAL_DELIVERED_SMS, 
        NVL(INTER_PARTIAL_RECEIVED_SEG , 0) AS INTER_PARTIAL_RECEIVED_SEG, 
        NVL(INTER_PARTIAL_RECEIVED_SMS , 0) AS INTER_PARTIAL_RECEIVED_SMS
FROM
(
SELECT /*+ PARALLEL(7) */
        trunc(processing_timestamp) AS processing_date, 
        extract(HOUR from processing_timestamp) AS processing_hour, 
        NVL(group_id,sender) AS group_id, 
        owner_id, 
        status_id, 
        segments_count, 
        (CASE substr(receiver, 1, 4) WHEN '2010' THEN 1 WHEN '2011' THEN 2 WHEN '2012' THEN 3 WHEN '2015' THEN 4 ELSE -1 END) AS rec, 
        (case nvl(GROUP_ID, 'API')  when 'API' then 2 else 1 end) AS stats_type 
FROM  sms_log 
WHERE processing_timestamp > (
            SELECT
                stats_last_update
            FROM
                stats_updates
            WHERE
                stats_id = 1)
      AND processing_timestamp <= v_end_date
) PIVOT (
        SUM(segments_count) AS SEG, COUNT(1) AS SMS FOR (status_id, rec) IN (
                (0, 1) vf_new, 
                (1, 1) vf_submitted, 
                (2, 1) vf_sent, 
                (3, 1) vf_timed_out, 
                (4, 1) vf_failed_to_send, 
                (5, 1) vf_delivered, 
                (6, 1) vf_not_delivered, 
                (7, 1) vf_failed, 
                (8, 1) vf_received, 
                (9, 1) vf_expired, 
                (10, 1) vf_unknown, 
                (11, 1) vf_processing, 
                (12, 1) vf_partial_delivered, 
                (13, 1) vf_partial_received, 
                (0, 2) et_new, 
                (1, 2) et_submitted, 
                (2, 2) et_sent, 
                (3, 2) et_timed_out, 
                (4, 2) et_failed_to_send, 
                (5, 2) et_delivered, 
                (6, 2) et_not_delivered, 
                (7, 2) et_failed, 
                (8, 2) et_received, 
                (9, 2) et_expired, 
                (10, 2) et_unknown, 
                (11, 2) et_processing, 
                (12, 2) et_partial_delivered, 
                (13, 2) et_partial_received, 
                (0, 3) OG_new, 
                (1, 3) OG_submitted, 
                (2, 3) OG_sent, 
                (3, 3) OG_timed_out, 
                (4, 3) OG_failed_to_send, 
                (5, 3) OG_delivered, 
                (6, 3) OG_not_delivered, 
                (7, 3) OG_failed, 
                (8, 3) OG_received, 
                (9, 3) OG_expired, 
                (10, 3) OG_unknown, 
                (11, 3) OG_processing, 
                (12, 3) OG_partial_delivered, 
                (13, 3) OG_partial_received, 
                (0, 4) we_new, 
                (1, 4) we_submitted, 
                (2, 4) we_sent, 
                (3, 4) we_timed_out, 
                (4, 4) we_failed_to_send, 
                (5, 4) we_delivered, 
                (6, 4) we_not_delivered, 
                (7, 4) we_failed, 
                (8, 4) we_received, 
                (9, 4) we_expired, 
                (10, 4) we_unknown, 
                (11, 4) we_processing, 
                (12, 4) we_partial_delivered, 
                (13, 4) we_partial_received, 
                (0,-1) inter_new, 
                (1,-1) inter_submitted, 
                (2,-1) inter_sent, 
                (3,-1) inter_timed_out, 
                (4,-1) inter_failed_to_send, 
                (5,-1) inter_delivered, 
                (6,-1) inter_not_delivered, 
                (7,-1) inter_failed, 
                (8,-1) inter_received, 
                (9,-1) inter_expired, 
                (10,-1) inter_unknown, 
                (11,-1) inter_processing, 
                (12,-1) inter_partial_delivered, 
                (13,-1) inter_partial_received
        )
     ) ;
BEGIN
    v_new_last_update_timestamp := TO_TIMESTAMP(TO_CHAR(SYSTIMESTAMP - INTERVAL '1' day, 'DD-MON-YY HH24'), 'DD-MON-YY HH24');

-- start loop
    FOR stat_rec IN sms_update_set(v_new_last_update_timestamp) LOOP BEGIN
        INSERT INTO collection_stats VALUES (
                stat_rec.PROCESSING_DATE,
                stat_rec.PROCESSING_HOUR,
                stat_rec.GROUP_ID,
                stat_rec.OWNER_ID,
                stat_rec.STATS_TYPE,
                
                stat_rec.VF_NEW_SEG,
                stat_rec.VF_NEW_SMS,
                stat_rec.VF_SUBMITTED_SEG,
                stat_rec.VF_SUBMITTED_SMS,
                stat_rec.VF_SENT_SEG,
                stat_rec.VF_SENT_SMS,
                stat_rec.VF_TIMED_OUT_SEG,
                stat_rec.VF_TIMED_OUT_SMS,
                stat_rec.VF_FAILED_TO_SEND_SEG,
                stat_rec.VF_FAILED_TO_SEND_SMS,
                stat_rec.VF_DELIVERED_SEG,
                stat_rec.VF_DELIVERED_SMS,
                stat_rec.VF_NOT_DELIVERED_SEG,
                stat_rec.VF_NOT_DELIVERED_SMS,
                stat_rec.VF_FAILED_SEG,
                stat_rec.VF_FAILED_SMS,
                stat_rec.VF_RECEIVED_SEG,
                stat_rec.VF_RECEIVED_SMS,
                stat_rec.VF_EXPIRED_SEG,
                stat_rec.VF_EXPIRED_SMS,
                stat_rec.VF_UNKNOWN_SEG,
                stat_rec.VF_UNKNOWN_SMS,
                stat_rec.VF_PROCESSING_SEG,
                stat_rec.VF_PROCESSING_SMS,
                stat_rec.VF_PARTIAL_DELIVERED_SEG,
                stat_rec.VF_PARTIAL_DELIVERED_SMS,
                stat_rec.VF_PARTIAL_RECEIVED_SEG,
                stat_rec.VF_PARTIAL_RECEIVED_SMS,
                
                stat_rec.ET_NEW_SEG,
                stat_rec.ET_NEW_SMS,
                stat_rec.ET_SUBMITTED_SEG,
                stat_rec.ET_SUBMITTED_SMS,
                stat_rec.ET_SENT_SEG,
                stat_rec.ET_SENT_SMS,
                stat_rec.ET_TIMED_OUT_SEG,
                stat_rec.ET_TIMED_OUT_SMS,
                stat_rec.ET_FAILED_TO_SEND_SEG,
                stat_rec.ET_FAILED_TO_SEND_SMS,
                stat_rec.ET_DELIVERED_SEG,
                stat_rec.ET_DELIVERED_SMS,
                stat_rec.ET_NOT_DELIVERED_SEG,
                stat_rec.ET_NOT_DELIVERED_SMS,
                stat_rec.ET_FAILED_SEG,
                stat_rec.ET_FAILED_SMS,
                stat_rec.ET_RECEIVED_SEG,
                stat_rec.ET_RECEIVED_SMS,
                stat_rec.ET_EXPIRED_SEG,
                stat_rec.ET_EXPIRED_SMS,
                stat_rec.ET_UNKNOWN_SEG,
                stat_rec.ET_UNKNOWN_SMS,
                stat_rec.ET_PROCESSING_SEG,
                stat_rec.ET_PROCESSING_SMS,
                stat_rec.ET_PARTIAL_DELIVERED_SEG,
                stat_rec.ET_PARTIAL_DELIVERED_SMS,
                stat_rec.ET_PARTIAL_RECEIVED_SEG,
                stat_rec.ET_PARTIAL_RECEIVED_SMS,
                
                stat_rec.OG_NEW_SEG,
                stat_rec.OG_NEW_SMS,
                stat_rec.OG_SUBMITTED_SEG,
                stat_rec.OG_SUBMITTED_SMS,
                stat_rec.OG_SENT_SEG,
                stat_rec.OG_SENT_SMS,
                stat_rec.OG_TIMED_OUT_SEG,
                stat_rec.OG_TIMED_OUT_SMS,
                stat_rec.OG_FAILED_TO_SEND_SEG,
                stat_rec.OG_FAILED_TO_SEND_SMS,
                stat_rec.OG_DELIVERED_SEG,
                stat_rec.OG_DELIVERED_SMS,
                stat_rec.OG_NOT_DELIVERED_SEG,
                stat_rec.OG_NOT_DELIVERED_SMS,
                stat_rec.OG_FAILED_SEG,
                stat_rec.OG_FAILED_SMS,
                stat_rec.OG_RECEIVED_SEG,
                stat_rec.OG_RECEIVED_SMS,
                stat_rec.OG_EXPIRED_SEG,
                stat_rec.OG_EXPIRED_SMS,
                stat_rec.OG_UNKNOWN_SEG,
                stat_rec.OG_UNKNOWN_SMS,
                stat_rec.OG_PROCESSING_SEG,
                stat_rec.OG_PROCESSING_SMS,
                stat_rec.OG_PARTIAL_DELIVERED_SEG,
                stat_rec.OG_PARTIAL_DELIVERED_SMS,
                stat_rec.OG_PARTIAL_RECEIVED_SEG,
                stat_rec.OG_PARTIAL_RECEIVED_SMS,
                
                stat_rec.WE_NEW_SEG,
                stat_rec.WE_NEW_SMS,
                stat_rec.WE_SUBMITTED_SEG,
                stat_rec.WE_SUBMITTED_SMS,
                stat_rec.WE_SENT_SEG,
                stat_rec.WE_SENT_SMS,
                stat_rec.WE_TIMED_OUT_SEG,
                stat_rec.WE_TIMED_OUT_SMS,
                stat_rec.WE_FAILED_TO_SEND_SEG,
                stat_rec.WE_FAILED_TO_SEND_SMS,
                stat_rec.WE_DELIVERED_SEG,
                stat_rec.WE_DELIVERED_SMS,
                stat_rec.WE_NOT_DELIVERED_SEG,
                stat_rec.WE_NOT_DELIVERED_SMS,
                stat_rec.WE_FAILED_SEG,
                stat_rec.WE_FAILED_SMS,
                stat_rec.WE_RECEIVED_SEG,
                stat_rec.WE_RECEIVED_SMS,
                stat_rec.WE_EXPIRED_SEG,
                stat_rec.WE_EXPIRED_SMS,
                stat_rec.WE_UNKNOWN_SEG,
                stat_rec.WE_UNKNOWN_SMS,
                stat_rec.WE_PROCESSING_SEG,
                stat_rec.WE_PROCESSING_SMS,
                stat_rec.WE_PARTIAL_DELIVERED_SEG,
                stat_rec.WE_PARTIAL_DELIVERED_SMS,
                stat_rec.WE_PARTIAL_RECEIVED_SEG,
                stat_rec.WE_PARTIAL_RECEIVED_SMS,
                
                stat_rec.INTER_NEW_SEG,
                stat_rec.INTER_NEW_SMS,
                stat_rec.INTER_SUBMITTED_SEG,
                stat_rec.INTER_SUBMITTED_SMS,
                stat_rec.INTER_SENT_SEG,
                stat_rec.INTER_SENT_SMS,
                stat_rec.INTER_TIMED_OUT_SEG,
                stat_rec.INTER_TIMED_OUT_SMS,
                stat_rec.INTER_FAILED_TO_SEND_SEG,
                stat_rec.INTER_FAILED_TO_SEND_SMS,
                stat_rec.INTER_DELIVERED_SEG,
                stat_rec.INTER_DELIVERED_SMS,
                stat_rec.INTER_NOT_DELIVERED_SEG,
                stat_rec.INTER_NOT_DELIVERED_SMS,
                stat_rec.INTER_FAILED_SEG,
                stat_rec.INTER_FAILED_SMS,
                stat_rec.INTER_RECEIVED_SEG,
                stat_rec.INTER_RECEIVED_SMS,
                stat_rec.INTER_EXPIRED_SEG,
                stat_rec.INTER_EXPIRED_SMS,
                stat_rec.INTER_UNKNOWN_SEG,
                stat_rec.INTER_UNKNOWN_SMS,
                stat_rec.INTER_PROCESSING_SEG,
                stat_rec.INTER_PROCESSING_SMS,
                stat_rec.INTER_PARTIAL_DELIVERED_SEG,
                stat_rec.INTER_PARTIAL_DELIVERED_SMS,
                stat_rec.INTER_PARTIAL_RECEIVED_SEG,
                stat_rec.INTER_PARTIAL_RECEIVED_SMS
        );
    EXCEPTION
        WHEN dup_val_on_index THEN
                UPDATE collection_stats
                SET
                        VF_NEW_SEG = VF_NEW_SEG + stat_rec.VF_NEW_SEG, 
                        VF_NEW_SMS = VF_NEW_SMS + stat_rec.VF_NEW_SMS, 
                        VF_SUBMITTED_SEG = VF_SUBMITTED_SEG + stat_rec.VF_SUBMITTED_SEG, 
                        VF_SUBMITTED_SMS = VF_SUBMITTED_SMS + stat_rec.VF_SUBMITTED_SMS, 
                        VF_SENT_SEG = VF_SENT_SEG + stat_rec.VF_SENT_SEG, 
                        VF_SENT_SMS = VF_SENT_SMS + stat_rec.VF_SENT_SMS, 
                        VF_TIMED_OUT_SEG = VF_TIMED_OUT_SEG + stat_rec.VF_TIMED_OUT_SEG, 
                        VF_TIMED_OUT_SMS = VF_TIMED_OUT_SMS + stat_rec.VF_TIMED_OUT_SMS, 
                        VF_FAILED_TO_SEND_SEG = VF_FAILED_TO_SEND_SEG + stat_rec.VF_FAILED_TO_SEND_SEG, 
                        VF_FAILED_TO_SEND_SMS = VF_FAILED_TO_SEND_SMS + stat_rec.VF_FAILED_TO_SEND_SMS, 
                        VF_DELIVERED_SEG = VF_DELIVERED_SEG + stat_rec.VF_DELIVERED_SEG, 
                        VF_DELIVERED_SMS = VF_DELIVERED_SMS + stat_rec.VF_DELIVERED_SMS, 
                        VF_NOT_DELIVERED_SEG = VF_NOT_DELIVERED_SEG + stat_rec.VF_NOT_DELIVERED_SEG, 
                        VF_NOT_DELIVERED_SMS = VF_NOT_DELIVERED_SMS + stat_rec.VF_NOT_DELIVERED_SMS, 
                        VF_FAILED_SEG = VF_FAILED_SEG + stat_rec.VF_FAILED_SEG, 
                        VF_FAILED_SMS = VF_FAILED_SMS + stat_rec.VF_FAILED_SMS, 
                        VF_RECEIVED_SEG = VF_RECEIVED_SEG + stat_rec.VF_RECEIVED_SEG, 
                        VF_RECEIVED_SMS = VF_RECEIVED_SMS + stat_rec.VF_RECEIVED_SMS, 
                        VF_EXPIRED_SEG = VF_EXPIRED_SEG + stat_rec.VF_EXPIRED_SEG, 
                        VF_EXPIRED_SMS = VF_EXPIRED_SMS + stat_rec.VF_EXPIRED_SMS, 
                        VF_UNKNOWN_SEG = VF_UNKNOWN_SEG + stat_rec.VF_UNKNOWN_SEG, 
                        VF_UNKNOWN_SMS = VF_UNKNOWN_SMS + stat_rec.VF_UNKNOWN_SMS, 
                        VF_PROCESSING_SEG = VF_PROCESSING_SEG + stat_rec.VF_PROCESSING_SEG, 
                        VF_PROCESSING_SMS = VF_PROCESSING_SMS + stat_rec.VF_PROCESSING_SMS, 
                        VF_PARTIAL_DELIVERED_SEG = VF_PARTIAL_DELIVERED_SEG + stat_rec.VF_PARTIAL_DELIVERED_SEG, 
                        VF_PARTIAL_DELIVERED_SMS = VF_PARTIAL_DELIVERED_SMS + stat_rec.VF_PARTIAL_DELIVERED_SMS, 
                        VF_PARTIAL_RECEIVED_SEG = VF_PARTIAL_RECEIVED_SEG + stat_rec.VF_PARTIAL_RECEIVED_SEG, 
                        VF_PARTIAL_RECEIVED_SMS = VF_PARTIAL_RECEIVED_SMS + stat_rec.VF_PARTIAL_RECEIVED_SMS, 


                        ET_NEW_SEG = ET_NEW_SEG + stat_rec.ET_NEW_SEG, 
                        ET_NEW_SMS = ET_NEW_SMS + stat_rec.ET_NEW_SMS, 
                        ET_SUBMITTED_SEG = ET_SUBMITTED_SEG + stat_rec.ET_SUBMITTED_SEG, 
                        ET_SUBMITTED_SMS = ET_SUBMITTED_SMS + stat_rec.ET_SUBMITTED_SMS, 
                        ET_SENT_SEG = ET_SENT_SEG + stat_rec.ET_SENT_SEG, 
                        ET_SENT_SMS = ET_SENT_SMS + stat_rec.ET_SENT_SMS, 
                        ET_TIMED_OUT_SEG = ET_TIMED_OUT_SEG + stat_rec.ET_TIMED_OUT_SEG, 
                        ET_TIMED_OUT_SMS = ET_TIMED_OUT_SMS + stat_rec.ET_TIMED_OUT_SMS, 
                        ET_FAILED_TO_SEND_SEG = ET_FAILED_TO_SEND_SEG + stat_rec.ET_FAILED_TO_SEND_SEG, 
                        ET_FAILED_TO_SEND_SMS = ET_FAILED_TO_SEND_SMS + stat_rec.ET_FAILED_TO_SEND_SMS, 
                        ET_DELIVERED_SEG = ET_DELIVERED_SEG + stat_rec.ET_DELIVERED_SEG, 
                        ET_DELIVERED_SMS = ET_DELIVERED_SMS + stat_rec.ET_DELIVERED_SMS, 
                        ET_NOT_DELIVERED_SEG = ET_NOT_DELIVERED_SEG + stat_rec.ET_NOT_DELIVERED_SEG, 
                        ET_NOT_DELIVERED_SMS = ET_NOT_DELIVERED_SMS + stat_rec.ET_NOT_DELIVERED_SMS, 
                        ET_FAILED_SEG = ET_FAILED_SEG + stat_rec.ET_FAILED_SEG, 
                        ET_FAILED_SMS = ET_FAILED_SMS + stat_rec.ET_FAILED_SMS, 
                        ET_RECEIVED_SEG = ET_RECEIVED_SEG + stat_rec.ET_RECEIVED_SEG, 
                        ET_RECEIVED_SMS = ET_RECEIVED_SMS + stat_rec.ET_RECEIVED_SMS, 
                        ET_EXPIRED_SEG = ET_EXPIRED_SEG + stat_rec.ET_EXPIRED_SEG, 
                        ET_EXPIRED_SMS = ET_EXPIRED_SMS + stat_rec.ET_EXPIRED_SMS, 
                        ET_UNKNOWN_SEG = ET_UNKNOWN_SEG + stat_rec.ET_UNKNOWN_SEG, 
                        ET_UNKNOWN_SMS = ET_UNKNOWN_SMS + stat_rec.ET_UNKNOWN_SMS, 
                        ET_PROCESSING_SEG = ET_PROCESSING_SEG + stat_rec.ET_PROCESSING_SEG, 
                        ET_PROCESSING_SMS = ET_PROCESSING_SMS + stat_rec.ET_PROCESSING_SMS, 
                        ET_PARTIAL_DELIVERED_SEG = ET_PARTIAL_DELIVERED_SEG + stat_rec.ET_PARTIAL_DELIVERED_SEG, 
                        ET_PARTIAL_DELIVERED_SMS = ET_PARTIAL_DELIVERED_SMS + stat_rec.ET_PARTIAL_DELIVERED_SMS, 
                        ET_PARTIAL_RECEIVED_SEG = ET_PARTIAL_RECEIVED_SEG + stat_rec.ET_PARTIAL_RECEIVED_SEG, 
                        ET_PARTIAL_RECEIVED_SMS = ET_PARTIAL_RECEIVED_SMS + stat_rec.ET_PARTIAL_RECEIVED_SMS, 


                        OG_NEW_SEG = OG_NEW_SEG + stat_rec.OG_NEW_SEG, 
                        OG_NEW_SMS = OG_NEW_SMS + stat_rec.OG_NEW_SMS, 
                        OG_SUBMITTED_SEG = OG_SUBMITTED_SEG + stat_rec.OG_SUBMITTED_SEG, 
                        OG_SUBMITTED_SMS = OG_SUBMITTED_SMS + stat_rec.OG_SUBMITTED_SMS, 
                        OG_SENT_SEG = OG_SENT_SEG + stat_rec.OG_SENT_SEG, 
                        OG_SENT_SMS = OG_SENT_SMS + stat_rec.OG_SENT_SMS, 
                        OG_TIMED_OUT_SEG = OG_TIMED_OUT_SEG + stat_rec.OG_TIMED_OUT_SEG, 
                        OG_TIMED_OUT_SMS = OG_TIMED_OUT_SMS + stat_rec.OG_TIMED_OUT_SMS, 
                        OG_FAILED_TO_SEND_SEG = OG_FAILED_TO_SEND_SEG + stat_rec.OG_FAILED_TO_SEND_SEG, 
                        OG_FAILED_TO_SEND_SMS = OG_FAILED_TO_SEND_SMS + stat_rec.OG_FAILED_TO_SEND_SMS, 
                        OG_DELIVERED_SEG = OG_DELIVERED_SEG + stat_rec.OG_DELIVERED_SEG, 
                        OG_DELIVERED_SMS = OG_DELIVERED_SMS + stat_rec.OG_DELIVERED_SMS, 
                        OG_NOT_DELIVERED_SEG = OG_NOT_DELIVERED_SEG + stat_rec.OG_NOT_DELIVERED_SEG, 
                        OG_NOT_DELIVERED_SMS = OG_NOT_DELIVERED_SMS + stat_rec.OG_NOT_DELIVERED_SMS, 
                        OG_FAILED_SEG = OG_FAILED_SEG + stat_rec.OG_FAILED_SEG, 
                        OG_FAILED_SMS = OG_FAILED_SMS + stat_rec.OG_FAILED_SMS, 
                        OG_RECEIVED_SEG = OG_RECEIVED_SEG + stat_rec.OG_RECEIVED_SEG, 
                        OG_RECEIVED_SMS = OG_RECEIVED_SMS + stat_rec.OG_RECEIVED_SMS, 
                        OG_EXPIRED_SEG = OG_EXPIRED_SEG + stat_rec.OG_EXPIRED_SEG, 
                        OG_EXPIRED_SMS = OG_EXPIRED_SMS + stat_rec.OG_EXPIRED_SMS, 
                        OG_UNKNOWN_SEG = OG_UNKNOWN_SEG + stat_rec.OG_UNKNOWN_SEG, 
                        OG_UNKNOWN_SMS = OG_UNKNOWN_SMS + stat_rec.OG_UNKNOWN_SMS, 
                        OG_PROCESSING_SEG = OG_PROCESSING_SEG + stat_rec.OG_PROCESSING_SEG, 
                        OG_PROCESSING_SMS = OG_PROCESSING_SMS + stat_rec.OG_PROCESSING_SMS, 
                        OG_PARTIAL_DELIVERED_SEG = OG_PARTIAL_DELIVERED_SEG + stat_rec.OG_PARTIAL_DELIVERED_SEG, 
                        OG_PARTIAL_DELIVERED_SMS = OG_PARTIAL_DELIVERED_SMS + stat_rec.OG_PARTIAL_DELIVERED_SMS, 
                        OG_PARTIAL_RECEIVED_SEG = OG_PARTIAL_RECEIVED_SEG + stat_rec.OG_PARTIAL_RECEIVED_SEG, 
                        OG_PARTIAL_RECEIVED_SMS = OG_PARTIAL_RECEIVED_SMS + stat_rec.OG_PARTIAL_RECEIVED_SMS, 


                        WE_NEW_SEG = WE_NEW_SEG + stat_rec.WE_NEW_SEG, 
                        WE_NEW_SMS = WE_NEW_SMS + stat_rec.WE_NEW_SMS, 
                        WE_SUBMITTED_SEG = WE_SUBMITTED_SEG + stat_rec.WE_SUBMITTED_SEG, 
                        WE_SUBMITTED_SMS = WE_SUBMITTED_SMS + stat_rec.WE_SUBMITTED_SMS, 
                        WE_SENT_SEG = WE_SENT_SEG + stat_rec.WE_SENT_SEG, 
                        WE_SENT_SMS = WE_SENT_SMS + stat_rec.WE_SENT_SMS, 
                        WE_TIMED_OUT_SEG = WE_TIMED_OUT_SEG + stat_rec.WE_TIMED_OUT_SEG, 
                        WE_TIMED_OUT_SMS = WE_TIMED_OUT_SMS + stat_rec.WE_TIMED_OUT_SMS, 
                        WE_FAILED_TO_SEND_SEG = WE_FAILED_TO_SEND_SEG + stat_rec.WE_FAILED_TO_SEND_SEG, 
                        WE_FAILED_TO_SEND_SMS = WE_FAILED_TO_SEND_SMS + stat_rec.WE_FAILED_TO_SEND_SMS, 
                        WE_DELIVERED_SEG = WE_DELIVERED_SEG + stat_rec.WE_DELIVERED_SEG, 
                        WE_DELIVERED_SMS = WE_DELIVERED_SMS + stat_rec.WE_DELIVERED_SMS, 
                        WE_NOT_DELIVERED_SEG = WE_NOT_DELIVERED_SEG + stat_rec.WE_NOT_DELIVERED_SEG, 
                        WE_NOT_DELIVERED_SMS = WE_NOT_DELIVERED_SMS + stat_rec.WE_NOT_DELIVERED_SMS, 
                        WE_FAILED_SEG = WE_FAILED_SEG + stat_rec.WE_FAILED_SEG, 
                        WE_FAILED_SMS = WE_FAILED_SMS + stat_rec.WE_FAILED_SMS, 
                        WE_RECEIVED_SEG = WE_RECEIVED_SEG + stat_rec.WE_RECEIVED_SEG, 
                        WE_RECEIVED_SMS = WE_RECEIVED_SMS + stat_rec.WE_RECEIVED_SMS, 
                        WE_EXPIRED_SEG = WE_EXPIRED_SEG + stat_rec.WE_EXPIRED_SEG, 
                        WE_EXPIRED_SMS = WE_EXPIRED_SMS + stat_rec.WE_EXPIRED_SMS, 
                        WE_UNKNOWN_SEG = WE_UNKNOWN_SEG + stat_rec.WE_UNKNOWN_SEG, 
                        WE_UNKNOWN_SMS = WE_UNKNOWN_SMS + stat_rec.WE_UNKNOWN_SMS, 
                        WE_PROCESSING_SEG = WE_PROCESSING_SEG + stat_rec.WE_PROCESSING_SEG, 
                        WE_PROCESSING_SMS = WE_PROCESSING_SMS + stat_rec.WE_PROCESSING_SMS, 
                        WE_PARTIAL_DELIVERED_SEG = WE_PARTIAL_DELIVERED_SEG + stat_rec.WE_PARTIAL_DELIVERED_SEG, 
                        WE_PARTIAL_DELIVERED_SMS = WE_PARTIAL_DELIVERED_SMS + stat_rec.WE_PARTIAL_DELIVERED_SMS, 
                        WE_PARTIAL_RECEIVED_SEG = WE_PARTIAL_RECEIVED_SEG + stat_rec.WE_PARTIAL_RECEIVED_SEG, 
                        WE_PARTIAL_RECEIVED_SMS = WE_PARTIAL_RECEIVED_SMS + stat_rec.WE_PARTIAL_RECEIVED_SMS, 


                        INTER_NEW_SEG = INTER_NEW_SEG + stat_rec.INTER_NEW_SEG, 
                        INTER_NEW_SMS = INTER_NEW_SMS + stat_rec.INTER_NEW_SMS, 
                        INTER_SUBMITTED_SEG = INTER_SUBMITTED_SEG + stat_rec.INTER_SUBMITTED_SEG, 
                        INTER_SUBMITTED_SMS = INTER_SUBMITTED_SMS + stat_rec.INTER_SUBMITTED_SMS, 
                        INTER_SENT_SEG = INTER_SENT_SEG + stat_rec.INTER_SENT_SEG, 
                        INTER_SENT_SMS = INTER_SENT_SMS + stat_rec.INTER_SENT_SMS, 
                        INTER_TIMED_OUT_SEG = INTER_TIMED_OUT_SEG + stat_rec.INTER_TIMED_OUT_SEG, 
                        INTER_TIMED_OUT_SMS = INTER_TIMED_OUT_SMS + stat_rec.INTER_TIMED_OUT_SMS, 
                        INTER_FAILED_TO_SEND_SEG = INTER_FAILED_TO_SEND_SEG + stat_rec.INTER_FAILED_TO_SEND_SEG, 
                        INTER_FAILED_TO_SEND_SMS = INTER_FAILED_TO_SEND_SMS + stat_rec.INTER_FAILED_TO_SEND_SMS, 
                        INTER_DELIVERED_SEG = INTER_DELIVERED_SEG + stat_rec.INTER_DELIVERED_SEG, 
                        INTER_DELIVERED_SMS = INTER_DELIVERED_SMS + stat_rec.INTER_DELIVERED_SMS, 
                        INTER_NOT_DELIVERED_SEG = INTER_NOT_DELIVERED_SEG + stat_rec.INTER_NOT_DELIVERED_SEG, 
                        INTER_NOT_DELIVERED_SMS = INTER_NOT_DELIVERED_SMS + stat_rec.INTER_NOT_DELIVERED_SMS, 
                        INTER_FAILED_SEG = INTER_FAILED_SEG + stat_rec.INTER_FAILED_SEG, 
                        INTER_FAILED_SMS = INTER_FAILED_SMS + stat_rec.INTER_FAILED_SMS, 
                        INTER_RECEIVED_SEG = INTER_RECEIVED_SEG + stat_rec.INTER_RECEIVED_SEG, 
                        INTER_RECEIVED_SMS = INTER_RECEIVED_SMS + stat_rec.INTER_RECEIVED_SMS, 
                        INTER_EXPIRED_SEG = INTER_EXPIRED_SEG + stat_rec.INTER_EXPIRED_SEG, 
                        INTER_EXPIRED_SMS = INTER_EXPIRED_SMS + stat_rec.INTER_EXPIRED_SMS, 
                        INTER_UNKNOWN_SEG = INTER_UNKNOWN_SEG + stat_rec.INTER_UNKNOWN_SEG, 
                        INTER_UNKNOWN_SMS = INTER_UNKNOWN_SMS + stat_rec.INTER_UNKNOWN_SMS, 
                        INTER_PROCESSING_SEG = INTER_PROCESSING_SEG + stat_rec.INTER_PROCESSING_SEG, 
                        INTER_PROCESSING_SMS = INTER_PROCESSING_SMS + stat_rec.INTER_PROCESSING_SMS, 
                        INTER_PARTIAL_DELIVERED_SEG = INTER_PARTIAL_DELIVERED_SEG + stat_rec.INTER_PARTIAL_DELIVERED_SEG, 
                        INTER_PARTIAL_DELIVERED_SMS = INTER_PARTIAL_DELIVERED_SMS + stat_rec.INTER_PARTIAL_DELIVERED_SMS, 
                        INTER_PARTIAL_RECEIVED_SEG = INTER_PARTIAL_RECEIVED_SEG + stat_rec.INTER_PARTIAL_RECEIVED_SEG, 
                        INTER_PARTIAL_RECEIVED_SMS = INTER_PARTIAL_RECEIVED_SMS + stat_rec.INTER_PARTIAL_RECEIVED_SMS 

                WHERE
                        PROCESSING_DATE = stat_rec.PROCESSING_DATE
                        AND PROCESSING_HOUR = stat_rec.PROCESSING_HOUR
                        AND GROUP_ID = stat_rec.GROUP_ID
                        AND OWNER_ID = stat_rec.OWNER_ID
                        AND STATS_TYPE = stat_rec.STATS_TYPE;
        END;
    END LOOP;
-- end loop

    UPDATE stats_updates
    SET
        stats_last_update = v_new_last_update_timestamp
    WHERE
        stats_id = 1;

    COMMIT;

END;

