package com.edafa.web2sms.service.enums;

public enum CampaignManagementResp {
	SUCCESS, INVALID_SENDER, FAIL, INVALID_REQUEST, INVALID_ACCOUNT_STATE, DUPLICAT_CAMPAIGN_NAME, INVALID_SMS_TEXT, INVALID_CAMPAIGN_STATE;
}
