//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 02:16:38 PM EEST 
//

package com.edafa.web2sms.prov.tibco.types;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.edafa.web2sms.dalayer.enums.AccountStatusName;
import com.edafa.web2sms.acc_manag.service.model.TierModel;

/**
 * <p>
 * Java class for accountInfo complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="accountInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.edafa.com/web2sms/prov/TIBCO}provisioningStatus">
 *       &lt;sequence>
 *         &lt;element name="accountId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="3"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="accountStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="3"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rateplan" type="{http://www.edafa.com/web2sms/prov/TIBCO}ratePlan"/>
 *         &lt;element name="senderName" type="{http://www.edafa.com/web2sms/prov/TIBCO}senderName"/>
 *         &lt;element name="pendingRequests" type="{http://www.edafa.com/web2sms/prov/TIBCO}pendingProvRequest" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountInfo", propOrder = { "accountId", "accountStatus", "companyName", "accountAdmin",
		"billingMsisdn", "tier", "senderName", "pendingRequests" })
public class AccountInfo extends ProvisioningStatus {

	@XmlElement(required = false, nillable = false)
	protected String accountId;
	@XmlElement(name = "AccountStatus", required = false, nillable = false)
	protected AccountStatusName accountStatus;
	@XmlElement(required = false, nillable = false)
	protected String companyName;
	@XmlElement(required = false, nillable = false)
	protected String accountAdmin;
	@XmlElement(required = false, nillable = false)
	protected String billingMsisdn;
	@XmlElement(name = "Tier", required = false, nillable = false)
	protected TierModel tier;
	@XmlElement(required = false, nillable = false)
	protected List<String> senderName;
	@XmlElement(required = false, nillable = false)
	protected List<PendingProvRequest> pendingRequests;

	/**
	 * Gets the value of the accountId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * Sets the value of the accountId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAccountId(String value) {
		this.accountId = value;
	}

	/**
	 * Gets the value of the accountStatus property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public AccountStatusName getAccountStatus() {
		return accountStatus;
	}

	/**
	 * Sets the value of the accountStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAccountStatus(AccountStatusName value) {
		this.accountStatus = value;
	}

	/**
	 * Gets the value of the tier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public TierModel getTier() {
		return tier;
	}

	/**
	 * Sets the value of the tier property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTier(TierModel tier) {
		this.tier = tier;
	}

	/**
	 * Gets the value of the senderName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public List<String> getSenderName() {
		return senderName;
	}

	/**
	 * Sets the value of the senderName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSenderName(List<String> value) {
		this.senderName = value;
	}

	/**
	 * Gets the value of the companyAdmin property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAccountAdmin() {
		return accountAdmin;
	}

	/**
	 * @param companyAdmin
	 *            the companyAdmin to set
	 */
	public void setAccountAdmin(String accountAdmin) {
		this.accountAdmin = accountAdmin;
	}

	/**
	 * Gets the value of the companyName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * @param companyName
	 *            the companyName to set
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * Gets the value of the billingMsisdn property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBillingMsisdn() {
		return billingMsisdn;
	}

	/**
	 * @param billingMsisdn
	 *            the billingMsisdn to set
	 */
	public void setBillingMsisdn(String billingMsisdn) {
		this.billingMsisdn = billingMsisdn;
	}

	/**
	 * Gets the value of the pendingRequests property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the pendingRequests property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPendingRequests().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PendingProvRequest }
	 * 
	 * 
	 */
	public List<PendingProvRequest> getPendingRequests() {
		if (pendingRequests == null) {
			pendingRequests = new ArrayList<PendingProvRequest>();
		}
		return this.pendingRequests;
	}

}
