//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 02:16:38 PM EEST 
//

package com.edafa.web2sms.prov.tibco.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for activateServiceRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="activateServiceRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.edafa.com/web2sms/prov/TIBCO}provisioningRequest">
 *       &lt;sequence>
 *         &lt;element name="billingMSISDN" type="{http://www.edafa.com/web2sms/prov/TIBCO}internationalMSISDN"/>
 *         &lt;element name="ratePlan" type="{http://www.edafa.com/web2sms/prov/TIBCO}ratePlan"/>
 *         &lt;element name="senderName" type="{http://www.edafa.com/web2sms/prov/TIBCO}senderName"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "activateServiceRequest", propOrder = { "billingMSISDN", "ratePlan", "senderName" })
public class ActivateServiceRequest extends ProvisioningRequest {

	@XmlElement(nillable = false, required = true)
	protected String billingMSISDN;
	@XmlElement(nillable = false, required = true)
	protected String ratePlan;
	@XmlElement(nillable = false, required = true)
	protected String senderName;

	/**
	 * Gets the value of the billingMSISDN property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBillingMSISDN() {
		return billingMSISDN;
	}

	/**
	 * Sets the value of the billingMSISDN property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBillingMSISDN(String value) {
		this.billingMSISDN = value;
	}

	/**
	 * Gets the value of the ratePlan property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRatePlan() {
		return ratePlan;
	}

	/**
	 * Sets the value of the ratePlan property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRatePlan(String value) {
		this.ratePlan = value;
	}

	/**
	 * Gets the value of the senderName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSenderName() {
		return senderName;
	}

	/**
	 * Sets the value of the senderName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSenderName(String value) {
		this.senderName = value;
	}

	public boolean isValid() {
		return super.isValid()
				&& (isNonEmptyStr(billingMSISDN) && isNonEmptyStr(ratePlan) && isNonEmptyStr(senderName));
	}

	public String logInfo() {
		return "ActivateServiceRequest " + super.logInfo() + " billingMSISDN=" + billingMSISDN + ", ratePlan="
				+ ratePlan + ", senderName=" + senderName + ")";
	}

	boolean isNonEmptyStr(String s) {
		return (s != null && !s.isEmpty());
	}

}
