//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.05.19 at 02:16:38 PM EEST 
//


package com.edafa.web2sms.prov.tibco.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for changeSenderNameResponse complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="changeSenderNameResponse">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="returnStatus" type="{http://www.edafa.com/web2sms/prov/TIBCO}provisioningStatus"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "confirmSenderNameAddResponse", propOrder = {
 "returnStatus"
})
public class ConfirmSenderNameAddResponse {

 @XmlElement(required = true)
 protected ProvisioningStatus returnStatus;

 /**
  * Gets the value of the returnStatus property.
  * 
  * @return
  *     possible object is
  *     {@link ProvisioningStatus }
  *     
  */
 public ProvisioningStatus getReturnStatus() {
     return returnStatus;
 }

 /**
  * Sets the value of the returnStatus property.
  * 
  * @param value
  *     allowed object is
  *     {@link ProvisioningStatus }
  *     
  */
 public void setReturnStatus(ProvisioningStatus value) {
     this.returnStatus = value;
 }

}
