//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 02:16:38 PM EEST 
//


package com.edafa.web2sms.prov.tibco.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for confirmSenderNameChangeRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="confirmSenderNameChangeRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.edafa.com/web2sms/prov/TIBCO}provisioningRequest">
 *       &lt;sequence>
 *         &lt;element name="newSenderName" type="{http://www.edafa.com/web2sms/prov/TIBCO}senderName"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "confirmSenderNameChangeRequest", propOrder = {
    "oldSenderName", "newSenderName"
})
public class ConfirmSenderNameChangeRequest
    extends ProvisioningRequest
{

    @XmlElement(required = true, nillable = false)
    protected String oldSenderName;
    
    @XmlElement(required = true, nillable = false)
    protected String newSenderName;
    
    /**
     * Gets the value of the newSenderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldSenderName() {
        return oldSenderName;
    }

    /**
     * Sets the value of the newSenderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldSenderName(String value) {
        this.oldSenderName = value;
    }

    /**
     * Gets the value of the newSenderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewSenderName() {
        return newSenderName;
    }

    /**
     * Sets the value of the newSenderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewSenderName(String value) {
        this.newSenderName = value;
    }
    
    @Override
    public String toString(){
    	
    	return ("ConfirmSenderNameChangeRequest (requestId="+ requestId + ", old senderName="+ oldSenderName+", new senderName="+ newSenderName+").");
    	
    	
    }

}
