//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 02:16:38 PM EEST 
//

package com.edafa.web2sms.prov.tibco.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for getAccountInfoRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="getAccountInfoRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountHolderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAccountInfoRequest", propOrder = { "accountHolderId", "msisdn" })
public class GetAccountInfoRequest {

	@XmlElement(required = false, nillable = false)
	protected String accountHolderId;

	@XmlElement(required = false, nillable = false)
	protected String msisdn;

	/**
	 * Gets the value of the accountHolderId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAccountHolderId() {
		return accountHolderId;
	}

	/**
	 * Sets the value of the accountHolderId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAccountHolderId(String value) {
		this.accountHolderId = value;
	}

	/**
	 * Gets the value of the msisdn property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMSISDN() {
		return msisdn;
	}

	/**
	 * Sets the value of the msisdn property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMSISDN(String value) {
		this.msisdn = value;
	}

	public boolean isValid() {
		// return accountHolderId != null && !accountHolderId.isEmpty();
		return (accountHolderId != null && !accountHolderId.isEmpty())
				|| (msisdn != null && !msisdn.isEmpty() && msisdn.length() > 9);
	}

	@Override
	public String toString() {
		String message = "GetAccountInfoRequest (";
		
		if(accountHolderId == null){
			message+="";
		} else {
			message+="accountHolderId ="+accountHolderId;
		}
		if(msisdn != null){
			if(message.charAt(message.length()-1) != '(')
			{
				message+=", ";
			}
			message+= "MSISDN ="+msisdn;
		}  else{
			message+="";
		}
		message+=").";
		return message;
	}
}
