//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 02:16:38 PM EEST 
//


package com.edafa.web2sms.prov.tibco.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.edafa.web2sms.service.prov.tibco.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CancelProvRequestResponse_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "cancelProvRequestResponse");
    private final static QName _ChangeSenderNameRequest_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "changeSenderNameRequest");
    private final static QName _DowngradeServiceRequest_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "downgradeServiceRequest");
    private final static QName _DowngradeServiceResponse_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "downgradeServiceResponse");
    private final static QName _UpgradeServiceRequest_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "upgradeServiceRequest");
    private final static QName _DeactivateServiceRequest_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "deactivateServiceRequest");
    private final static QName _AccountInfo_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "accountInfo");
    private final static QName _CancelProvRequestRequest_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "cancelProvRequestRequest");
    private final static QName _ConfirmSenderNameChangeRequest_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "confirmSenderNameChangeRequest");
    private final static QName _ConfirmSenderNameChangeResponse_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "confirmSenderNameChangeResponse");
    private final static QName _ChangeSenderNameResponse_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "changeSenderNameResponse");
    private final static QName _ActivateServiceResponse_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "activateServiceResponse");
    private final static QName _DeactivateServiceResponse_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "deactivateServiceResponse");
    private final static QName _ProvisioningStatus_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "provisioningStatus");
    private final static QName _GetAccountInfoRequest_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "getAccountInfoRequest");
    private final static QName _ProvisioningRequest_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "provisioningRequest");
    private final static QName _UpgradeServiceResponse_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "upgradeServiceResponse");
    private final static QName _GetAccountInfoResponse_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "getAccountInfoResponse");
    private final static QName _ActivateServiceRequest_QNAME = new QName("http://www.edafa.com/web2sms/prov/TIBCO", "activateServiceRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.edafa.web2sms.service.prov.tibco.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChangeSenderNameResponse }
     * 
     */
    public ChangeSenderNameResponse createChangeSenderNameResponse() {
        return new ChangeSenderNameResponse();
    }

    /**
     * Create an instance of {@link ConfirmSenderNameChangeResponse }
     * 
     */
    public ConfirmSenderNameChangeResponse createConfirmSenderNameChangeResponse() {
        return new ConfirmSenderNameChangeResponse();
    }

    /**
     * Create an instance of {@link AccountInfo }
     * 
     */
    public AccountInfo createAccountInfo() {
        return new AccountInfo();
    }

    /**
     * Create an instance of {@link CancelProvRequest }
     * 
     */
    public CancelProvRequest createCancelProvRequest() {
        return new CancelProvRequest();
    }

    /**
     * Create an instance of {@link ConfirmSenderNameChangeRequest }
     * 
     */
    public ConfirmSenderNameChangeRequest createConfirmSenderNameChangeRequest() {
        return new ConfirmSenderNameChangeRequest();
    }

    /**
     * Create an instance of {@link DowngradeServiceRequest }
     * 
     */
    public DowngradeServiceRequest createDowngradeServiceRequest() {
        return new DowngradeServiceRequest();
    }

    /**
     * Create an instance of {@link DowngradeServiceResponse }
     * 
     */
    public DowngradeServiceResponse createDowngradeServiceResponse() {
        return new DowngradeServiceResponse();
    }

    /**
     * Create an instance of {@link UpgradeServiceRequest }
     * 
     */
    public UpgradeServiceRequest createUpgradeServiceRequest() {
        return new UpgradeServiceRequest();
    }

    /**
     * Create an instance of {@link CancelProvRequestResponse }
     * 
     */
    public CancelProvRequestResponse createCancelProvRequestResponse() {
        return new CancelProvRequestResponse();
    }

    /**
     * Create an instance of {@link ChangeSenderNameRequest }
     * 
     */
    public ChangeSenderNameRequest createChangeSenderNameRequest() {
        return new ChangeSenderNameRequest();
    }

    /**
     * Create an instance of {@link DeactivateServiceRequest }
     * 
     */
    public DeactivateServiceRequest createDeactivateServiceRequest() {
        return new DeactivateServiceRequest();
    }

    /**
     * Create an instance of {@link GetAccountInfoResponse }
     * 
     */
    public GetAccountInfoResponse createGetAccountInfoResponse() {
        return new GetAccountInfoResponse();
    }

    /**
     * Create an instance of {@link ActivateServiceRequest }
     * 
     */
    public ActivateServiceRequest createActivateServiceRequest() {
        return new ActivateServiceRequest();
    }

    /**
     * Create an instance of {@link UpgradeServiceResponse }
     * 
     */
    public UpgradeServiceResponse createUpgradeServiceResponse() {
        return new UpgradeServiceResponse();
    }

    /**
     * Create an instance of {@link ProvisioningRequest }
     * 
     */
    public ProvisioningRequest createProvisioningRequest() {
        return new ProvisioningRequest();
    }

    /**
     * Create an instance of {@link GetAccountInfoRequest }
     * 
     */
    public GetAccountInfoRequest createGetAccountInfoRequest() {
        return new GetAccountInfoRequest();
    }

    /**
     * Create an instance of {@link ProvisioningStatus }
     * 
     */
    public ProvisioningStatus createProvisioningStatus() {
        return new ProvisioningStatus();
    }

    /**
     * Create an instance of {@link DeactivateServiceResponse }
     * 
     */
    public DeactivateServiceResponse createDeactivateServiceResponse() {
        return new DeactivateServiceResponse();
    }

    /**
     * Create an instance of {@link ActivateServiceResponse }
     * 
     */
    public ActivateServiceResponse createActivateServiceResponse() {
        return new ActivateServiceResponse();
    }

    /**
     * Create an instance of {@link PendingProvRequest }
     * 
     */
    public PendingProvRequest createPendingProvRequest() {
        return new PendingProvRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelProvRequestResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "cancelProvRequestResponse")
    public JAXBElement<CancelProvRequestResponse> createCancelProvRequestResponse(CancelProvRequestResponse value) {
        return new JAXBElement<CancelProvRequestResponse>(_CancelProvRequestResponse_QNAME, CancelProvRequestResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeSenderNameRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "changeSenderNameRequest")
    public JAXBElement<ChangeSenderNameRequest> createChangeSenderNameRequest(ChangeSenderNameRequest value) {
        return new JAXBElement<ChangeSenderNameRequest>(_ChangeSenderNameRequest_QNAME, ChangeSenderNameRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DowngradeServiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "downgradeServiceRequest")
    public JAXBElement<DowngradeServiceRequest> createDowngradeServiceRequest(DowngradeServiceRequest value) {
        return new JAXBElement<DowngradeServiceRequest>(_DowngradeServiceRequest_QNAME, DowngradeServiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DowngradeServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "downgradeServiceResponse")
    public JAXBElement<DowngradeServiceResponse> createDowngradeServiceResponse(DowngradeServiceResponse value) {
        return new JAXBElement<DowngradeServiceResponse>(_DowngradeServiceResponse_QNAME, DowngradeServiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpgradeServiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "upgradeServiceRequest")
    public JAXBElement<UpgradeServiceRequest> createUpgradeServiceRequest(UpgradeServiceRequest value) {
        return new JAXBElement<UpgradeServiceRequest>(_UpgradeServiceRequest_QNAME, UpgradeServiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeactivateServiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "deactivateServiceRequest")
    public JAXBElement<DeactivateServiceRequest> createDeactivateServiceRequest(DeactivateServiceRequest value) {
        return new JAXBElement<DeactivateServiceRequest>(_DeactivateServiceRequest_QNAME, DeactivateServiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "accountInfo")
    public JAXBElement<AccountInfo> createAccountInfo(AccountInfo value) {
        return new JAXBElement<AccountInfo>(_AccountInfo_QNAME, AccountInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelProvRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "cancelProvRequestRequest")
    public JAXBElement<CancelProvRequest> createCancelProvRequestRequest(CancelProvRequest value) {
        return new JAXBElement<CancelProvRequest>(_CancelProvRequestRequest_QNAME, CancelProvRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmSenderNameChangeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "confirmSenderNameChangeRequest")
    public JAXBElement<ConfirmSenderNameChangeRequest> createConfirmSenderNameChangeRequest(ConfirmSenderNameChangeRequest value) {
        return new JAXBElement<ConfirmSenderNameChangeRequest>(_ConfirmSenderNameChangeRequest_QNAME, ConfirmSenderNameChangeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmSenderNameChangeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "confirmSenderNameChangeResponse")
    public JAXBElement<ConfirmSenderNameChangeResponse> createConfirmSenderNameChangeResponse(ConfirmSenderNameChangeResponse value) {
        return new JAXBElement<ConfirmSenderNameChangeResponse>(_ConfirmSenderNameChangeResponse_QNAME, ConfirmSenderNameChangeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeSenderNameResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "changeSenderNameResponse")
    public JAXBElement<ChangeSenderNameResponse> createChangeSenderNameResponse(ChangeSenderNameResponse value) {
        return new JAXBElement<ChangeSenderNameResponse>(_ChangeSenderNameResponse_QNAME, ChangeSenderNameResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivateServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "activateServiceResponse")
    public JAXBElement<ActivateServiceResponse> createActivateServiceResponse(ActivateServiceResponse value) {
        return new JAXBElement<ActivateServiceResponse>(_ActivateServiceResponse_QNAME, ActivateServiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeactivateServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "deactivateServiceResponse")
    public JAXBElement<DeactivateServiceResponse> createDeactivateServiceResponse(DeactivateServiceResponse value) {
        return new JAXBElement<DeactivateServiceResponse>(_DeactivateServiceResponse_QNAME, DeactivateServiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProvisioningStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "provisioningStatus")
    public JAXBElement<ProvisioningStatus> createProvisioningStatus(ProvisioningStatus value) {
        return new JAXBElement<ProvisioningStatus>(_ProvisioningStatus_QNAME, ProvisioningStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountInfoRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "getAccountInfoRequest")
    public JAXBElement<GetAccountInfoRequest> createGetAccountInfoRequest(GetAccountInfoRequest value) {
        return new JAXBElement<GetAccountInfoRequest>(_GetAccountInfoRequest_QNAME, GetAccountInfoRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProvisioningRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "provisioningRequest")
    public JAXBElement<ProvisioningRequest> createProvisioningRequest(ProvisioningRequest value) {
        return new JAXBElement<ProvisioningRequest>(_ProvisioningRequest_QNAME, ProvisioningRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpgradeServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "upgradeServiceResponse")
    public JAXBElement<UpgradeServiceResponse> createUpgradeServiceResponse(UpgradeServiceResponse value) {
        return new JAXBElement<UpgradeServiceResponse>(_UpgradeServiceResponse_QNAME, UpgradeServiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "getAccountInfoResponse")
    public JAXBElement<GetAccountInfoResponse> createGetAccountInfoResponse(GetAccountInfoResponse value) {
        return new JAXBElement<GetAccountInfoResponse>(_GetAccountInfoResponse_QNAME, GetAccountInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivateServiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.edafa.com/web2sms/prov/TIBCO", name = "activateServiceRequest")
    public JAXBElement<ActivateServiceRequest> createActivateServiceRequest(ActivateServiceRequest value) {
        return new JAXBElement<ActivateServiceRequest>(_ActivateServiceRequest_QNAME, ActivateServiceRequest.class, null, value);
    }

}
