//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 02:16:38 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.edafa.com/web2sms/prov/TIBCO")
package com.edafa.web2sms.prov.tibco.types;
