//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 02:16:38 PM EEST 
//

package com.edafa.web2sms.prov.tibco.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.edafa.web2sms.dalayer.enums.ProvRequestTypeName;

/**
 * <p>
 * Java class for pendingProvRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="pendingProvRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trxId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requstType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="rateplan" type="{http://www.edafa.com/web2sms/prov/TIBCO}ratePlan"/>
 *         &lt;element name="senderName" type="{http://www.edafa.com/web2sms/prov/TIBCO}senderName"/>
 *         &lt;element name="newSenderName" type="{http://www.edafa.com/web2sms/prov/TIBCO}senderName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PendingProvRequest", propOrder = { "requestId", "requstType", "companyId", "companyName",
		"companyAdmin", "requestTimestamp", "rateplan", "senderName", "newSenderName" })
public class PendingProvRequest {

	@XmlElement(required = true, nillable = false)
	protected String requestId;
	@XmlElement(required = true, nillable = false)
	protected ProvRequestTypeName requstType;
	@XmlElement(required = true, nillable = false)
	protected String companyId;
	@XmlElement(required = true, nillable = false)
	protected String companyName;
	@XmlElement(required = true, nillable = false)
	protected String companyAdmin;
	@XmlElement(required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar requestTimestamp;
	@XmlElement(required = true, nillable = true)
	protected String rateplan;
	@XmlElement(required = true, nillable = true)
	protected String senderName;
	@XmlElement(required = true, nillable = true)
	protected String newSenderName;

	/**
	 * Gets the value of the trxId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRequestId() {
		return requestId;
	}

	/**
	 * Sets the value of the trxId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRequestId(String value) {
		this.requestId = value;
	}

	/**
	 * Gets the value of the requstType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public ProvRequestTypeName getRequstType() {
		return requstType;
	}

	/**
	 * Sets the value of the requstType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRequstType(ProvRequestTypeName value) {
		this.requstType = value;
	}

	/**
	 * Gets the value of the requestTimestamp property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getRequestTimestamp() {
		return requestTimestamp;
	}

	/**
	 * Sets the value of the requestTimestamp property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setRequestTimestamp(XMLGregorianCalendar value) {
		this.requestTimestamp = value;
	}

	/**
	 * Gets the value of the rateplan property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRateplan() {
		return rateplan;
	}

	/**
	 * Sets the value of the rateplan property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRateplan(String value) {
		this.rateplan = value;
	}

	/**
	 * Gets the value of the senderName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSenderName() {
		return senderName;
	}

	/**
	 * Sets the value of the senderName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSenderName(String value) {
		this.senderName = value;
	}

	public String getCompanyId() {
		return companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyAdmin() {
		return companyAdmin;
	}

	public void setCompanyAdmin(String companyAdmin) {
		this.companyAdmin = companyAdmin;
	}

	public String getNewSenderName() {
		return newSenderName;
	}

	public void setNewSenderName(String newSenderName) {
		this.newSenderName = newSenderName;
	}
	

}
