//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 02:16:38 PM EEST 
//

package com.edafa.web2sms.prov.tibco.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for upgradeServiceRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="upgradeServiceRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.edafa.com/web2sms/prov/TIBCO}provisioningRequest">
 *       &lt;sequence>
 *         &lt;element name="oldRatePlan" type="{http://www.edafa.com/web2sms/prov/TIBCO}ratePlan"/>
 *         &lt;element name="newRatePlan" type="{http://www.edafa.com/web2sms/prov/TIBCO}ratePlan"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "upgradeServiceRequest", propOrder = { "oldRatePlan", "newRatePlan" })
public class UpgradeServiceRequest extends ProvisioningRequest {

	@XmlElement(required = true, nillable = true)
	protected String oldRatePlan;
	@XmlElement(required = true)
	protected String newRatePlan;

	/**
	 * Gets the value of the oldRatePlan property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOldRatePlan() {
		return oldRatePlan;
	}

	/**
	 * Sets the value of the oldRatePlan property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOldRatePlan(String value) {
		this.oldRatePlan = value;
	}

	/**
	 * Gets the value of the newRatePlan property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNewRatePlan() {
		return newRatePlan;
	}

	/**
	 * Sets the value of the newRatePlan property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNewRatePlan(String value) {
		this.newRatePlan = value;
	}

	public boolean isValid() {
		return super.isValid() && isNonEmptyStr(newRatePlan);
	}

	public String logInfo() {
		return "UpgradeServiceRequest" + super.logInfo() + "ratePlan=" + newRatePlan + ")";
	}

	boolean isNonEmptyStr(String s) {
		return (s != null && !s.isEmpty());
	}

}
