package com.edafa.web2sms.dalayer.enums;

public enum SMSLogStatusType {
	ESME_RALYBND, ESME_RBINDFAIL, ESME_RCANCELFAIL, ESME_RINVBNDSTS, ESME_RINVCMDID, ESME_RINVCMDLEN, ESME_RINVDSTADR, ESME_RINVMSGID, ESME_RINVMSGLEN, ESME_RINVPASWD, ESME_RINVPRTFLG, ESME_RINVREGDLVFLG, ESME_RINVSRCADR, ESME_RINVSYSID, ESME_ROK, ESME_RREPLACEFAIL, ESME_RSYSERR, Enqued, FAILED_To_ENQUEUE, TIME_OUT, UNKNOW_ERROR, ESME_RTHROTTLED;
}
