//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.15 at 02:10:57 PM EEST 
//


package com.edafa.web2sms.prov.cloud.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="GenericProductProvision" type="{}CompanySubscriptionProvisionFullInfoType"/>
 *         &lt;element name="GenericProductUpgrade" type="{}CompanySubscriptionProvisionFullInfoType"/>
 *         &lt;element name="GenericProductDowngrade" type="{}CompanySubscriptionProvisionFullInfoType"/>
 *         &lt;element name="GenericProductSuspension" type="{}ProvisioningBaseType"/>
 *         &lt;element name="GenericProductActivation" type="{}ProvisioningBaseType"/>
 *         &lt;element name="GenericProductDelete" type="{}ProvisioningBaseType"/>
 *         &lt;element name="GenericProductUserCreate" type="{}CompanyUserProvisionFullInfoType"/>
 *         &lt;element name="GenericProductUserDelete" type="{}UserProvisionBaseType"/>
 *         &lt;element name="GenericProductUserAdminGrant" type="{}UserProvisionBaseType"/>
 *         &lt;element name="GenericProductUserAdminRevoke" type="{}UserProvisionBaseType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "genericProductProvision",
    "genericProductUpgrade",
    "genericProductDowngrade",
    "genericProductSuspension",
    "genericProductActivation",
    "genericProductDelete",
    "genericProductUserCreate",
    "genericProductUserDelete",
    "genericProductUserAdminGrant",
    "genericProductUserAdminRevoke"
})
@XmlRootElement(name = "GenericProductProvisionRequest")
public class GenericProductProvisionRequest {

    @XmlElement(name = "GenericProductProvision")
    protected CompanySubscriptionProvisionFullInfoType genericProductProvision;
    @XmlElement(name = "GenericProductUpgrade")
    protected CompanySubscriptionProvisionFullInfoType genericProductUpgrade;
    @XmlElement(name = "GenericProductDowngrade")
    protected CompanySubscriptionProvisionFullInfoType genericProductDowngrade;
    @XmlElement(name = "GenericProductSuspension")
    protected ProvisioningBaseType genericProductSuspension;
    @XmlElement(name = "GenericProductActivation")
    protected ProvisioningBaseType genericProductActivation;
    @XmlElement(name = "GenericProductDelete")
    protected ProvisioningBaseType genericProductDelete;
    @XmlElement(name = "GenericProductUserCreate")
    protected CompanyUserProvisionFullInfoType genericProductUserCreate;
    @XmlElement(name = "GenericProductUserDelete")
    protected UserProvisionBaseType genericProductUserDelete;
    @XmlElement(name = "GenericProductUserAdminGrant")
    protected UserProvisionBaseType genericProductUserAdminGrant;
    @XmlElement(name = "GenericProductUserAdminRevoke")
    protected UserProvisionBaseType genericProductUserAdminRevoke;

    /**
     * Gets the value of the genericProductProvision property.
     * 
     * @return
     *     possible object is
     *     {@link CompanySubscriptionProvisionFullInfoType }
     *     
     */
    public CompanySubscriptionProvisionFullInfoType getGenericProductProvision() {
        return genericProductProvision;
    }

    /**
     * Sets the value of the genericProductProvision property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanySubscriptionProvisionFullInfoType }
     *     
     */
    public void setGenericProductProvision(CompanySubscriptionProvisionFullInfoType value) {
        this.genericProductProvision = value;
    }

    /**
     * Gets the value of the genericProductUpgrade property.
     * 
     * @return
     *     possible object is
     *     {@link CompanySubscriptionProvisionFullInfoType }
     *     
     */
    public CompanySubscriptionProvisionFullInfoType getGenericProductUpgrade() {
        return genericProductUpgrade;
    }

    /**
     * Sets the value of the genericProductUpgrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanySubscriptionProvisionFullInfoType }
     *     
     */
    public void setGenericProductUpgrade(CompanySubscriptionProvisionFullInfoType value) {
        this.genericProductUpgrade = value;
    }

    /**
     * Gets the value of the genericProductDowngrade property.
     * 
     * @return
     *     possible object is
     *     {@link CompanySubscriptionProvisionFullInfoType }
     *     
     */
    public CompanySubscriptionProvisionFullInfoType getGenericProductDowngrade() {
        return genericProductDowngrade;
    }

    /**
     * Sets the value of the genericProductDowngrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanySubscriptionProvisionFullInfoType }
     *     
     */
    public void setGenericProductDowngrade(CompanySubscriptionProvisionFullInfoType value) {
        this.genericProductDowngrade = value;
    }

    /**
     * Gets the value of the genericProductSuspension property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisioningBaseType }
     *     
     */
    public ProvisioningBaseType getGenericProductSuspension() {
        return genericProductSuspension;
    }

    /**
     * Sets the value of the genericProductSuspension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisioningBaseType }
     *     
     */
    public void setGenericProductSuspension(ProvisioningBaseType value) {
        this.genericProductSuspension = value;
    }

    /**
     * Gets the value of the genericProductActivation property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisioningBaseType }
     *     
     */
    public ProvisioningBaseType getGenericProductActivation() {
        return genericProductActivation;
    }

    /**
     * Sets the value of the genericProductActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisioningBaseType }
     *     
     */
    public void setGenericProductActivation(ProvisioningBaseType value) {
        this.genericProductActivation = value;
    }

    /**
     * Gets the value of the genericProductDelete property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisioningBaseType }
     *     
     */
    public ProvisioningBaseType getGenericProductDelete() {
        return genericProductDelete;
    }

    /**
     * Sets the value of the genericProductDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisioningBaseType }
     *     
     */
    public void setGenericProductDelete(ProvisioningBaseType value) {
        this.genericProductDelete = value;
    }

    /**
     * Gets the value of the genericProductUserCreate property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyUserProvisionFullInfoType }
     *     
     */
    public CompanyUserProvisionFullInfoType getGenericProductUserCreate() {
        return genericProductUserCreate;
    }

    /**
     * Sets the value of the genericProductUserCreate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyUserProvisionFullInfoType }
     *     
     */
    public void setGenericProductUserCreate(CompanyUserProvisionFullInfoType value) {
        this.genericProductUserCreate = value;
    }

    /**
     * Gets the value of the genericProductUserDelete property.
     * 
     * @return
     *     possible object is
     *     {@link UserProvisionBaseType }
     *     
     */
    public UserProvisionBaseType getGenericProductUserDelete() {
        return genericProductUserDelete;
    }

    /**
     * Sets the value of the genericProductUserDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserProvisionBaseType }
     *     
     */
    public void setGenericProductUserDelete(UserProvisionBaseType value) {
        this.genericProductUserDelete = value;
    }

    /**
     * Gets the value of the genericProductUserAdminGrant property.
     * 
     * @return
     *     possible object is
     *     {@link UserProvisionBaseType }
     *     
     */
    public UserProvisionBaseType getGenericProductUserAdminGrant() {
        return genericProductUserAdminGrant;
    }

    /**
     * Sets the value of the genericProductUserAdminGrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserProvisionBaseType }
     *     
     */
    public void setGenericProductUserAdminGrant(UserProvisionBaseType value) {
        this.genericProductUserAdminGrant = value;
    }

    /**
     * Gets the value of the genericProductUserAdminRevoke property.
     * 
     * @return
     *     possible object is
     *     {@link UserProvisionBaseType }
     *     
     */
    public UserProvisionBaseType getGenericProductUserAdminRevoke() {
        return genericProductUserAdminRevoke;
    }

    /**
     * Sets the value of the genericProductUserAdminRevoke property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserProvisionBaseType }
     *     
     */
    public void setGenericProductUserAdminRevoke(UserProvisionBaseType value) {
        this.genericProductUserAdminRevoke = value;
    }

}
