//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.15 at 02:10:57 PM EEST 
//


package com.edafa.web2sms.prov.cloud.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.edafa.web2sms.service.prov.cloud.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.edafa.web2sms.service.prov.cloud.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenericProductProvisionRequest }
     * 
     */
    public GenericProductProvisionRequest createGenericProductProvisionRequest() {
        return new GenericProductProvisionRequest();
    }

    /**
     * Create an instance of {@link CompanySubscriptionProvisionFullInfoType }
     * 
     */
    public CompanySubscriptionProvisionFullInfoType createCompanySubscriptionProvisionFullInfoType() {
        return new CompanySubscriptionProvisionFullInfoType();
    }

    /**
     * Create an instance of {@link ProvisioningBaseType }
     * 
     */
    public ProvisioningBaseType createProvisioningBaseType() {
        return new ProvisioningBaseType();
    }

    /**
     * Create an instance of {@link CompanyUserProvisionFullInfoType }
     * 
     */
    public CompanyUserProvisionFullInfoType createCompanyUserProvisionFullInfoType() {
        return new CompanyUserProvisionFullInfoType();
    }

    /**
     * Create an instance of {@link UserProvisionBaseType }
     * 
     */
    public UserProvisionBaseType createUserProvisionBaseType() {
        return new UserProvisionBaseType();
    }

    /**
     * Create an instance of {@link OtherData }
     * 
     */
    public OtherData createOtherData() {
        return new OtherData();
    }

}
